channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:

    # Example command line software
    - nextflow=20.10.0
    - salmon=1.4.0

    # Example Python packages
    - python=3.6.12
    - argparse=1.4.0

    # Example R packages
    - bioconductor-tximport=1.14.0
    - r-base=3.6
    - r-tidyverse=1.3.0
